/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoestructurasdedatos;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import java.util.StringTokenizer;

/**
 *
 * @author santiago
 */
public class Interfaz extends javax.swing.JFrame {
    Empleado empleado = new Empleado();
    NodoEmpleadoLista nuevoNodo = new NodoEmpleadoLista();
    ListaDEnlazada lista = new ListaDEnlazada();
    TablaHashEnlazadaEmpleados tabla = new TablaHashEnlazadaEmpleados();
    /*
    String sucursal = "";
    
    TablaHashEnlazadaEmpleados tabla = new TablaHashEnlazadaEmpleados();
    
    ArregloEmpleados sucursal1 = new ArregloEmpleados(1);
    ArregloEmpleados sucursal2 = new ArregloEmpleados(2);
    ArregloEmpleados sucursal3 = new ArregloEmpleados(3);
    ArregloEmpleados sucursal4 = new ArregloEmpleados(4);
    */  
        
    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
        
        
        
        File archivo = null;
        FileReader fr = null;
        BufferedReader br = null;
        try{
            archivo = new File("registroEmpleados1.txt");
            fr = new FileReader(archivo);
            br = new BufferedReader(fr);
            String linea;
            while((linea = br.readLine()) != null){
                StringTokenizer tokens = new StringTokenizer(linea, ",");
                String dato = tokens.nextToken();
                Empleado nuevoEmpleado = new Empleado();
                nuevoEmpleado.setCodigo(dato);
                dato = tokens.nextToken();
                nuevoEmpleado.setNombres(dato);
                dato = tokens.nextToken();
                nuevoEmpleado.setApellidos(dato);
                dato = tokens.nextToken();
                nuevoEmpleado.setCargo(dato);
                dato = tokens.nextToken();
                nuevoEmpleado.setUltimaSucursal(dato);
                dato = tokens.nextToken();
                nuevoEmpleado.setDireccion(dato);
                dato = tokens.nextToken();
                nuevoEmpleado.setCorreo(dato);
                dato = tokens.nextToken();
                nuevoEmpleado.setNumTelf(dato);
                
                lista.insertarOrdenado(nuevoEmpleado);
                
                if (nuevoEmpleado.getCargo().equals("Vendedor")){
                    
                    tabla.inicializar(nuevoEmpleado.getCodigo(),nuevoEmpleado.getUltimaSucursal());
                }
            }
        }catch (Exception e){
            e.printStackTrace();
        }
        
        
        
        /*
        tabla.insertar(1, "10-0001");
        tabla.insertar(1, "10-0005");
        tabla.insertar(2, "10-0002");
        tabla.insertar(2, "10-0006");
        tabla.insertar(3, "10-0003");
        tabla.insertar(3, "10-0007");
        tabla.insertar(4, "10-0004");
        tabla.insertar(4, "10-0008");
        
        sucursal1.insertarEmpleado("Cristopher Santiago Pérez Nieto");
        sucursal1.insertarEmpleado("Ariel Thomás Rosero Peñaherrera");
        sucursal1.insertarEmpleado("Bryan Fernando Cedeño Mendoza");
        
        sucursal2.insertarEmpleado("Cristopher Santiago Pérez Nieto");
        sucursal2.insertarEmpleado("Ariel Thomás Rosero Peñaherrera");
        sucursal2.insertarEmpleado("Bryan Fernando Cedeño Mendoza");
        
        sucursal3.insertarEmpleado("Cristopher Santiago Pérez Nieto");
        sucursal3.insertarEmpleado("Ariel Thomás Rosero Peñaherrera");
        sucursal3.insertarEmpleado("Bryan Fernando Cedeño Mendoza");
        
        sucursal4.insertarEmpleado("Cristopher Santiago Pérez Nieto");
        sucursal4.insertarEmpleado("Ariel Thomás Rosero Peñaherrera");
        sucursal4.insertarEmpleado("Bryan Fernando Cedeño Mendoza");
        */
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        lblNombres = new javax.swing.JLabel();
        lblApellidos = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtApellidos = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        txtNumTelf = new javax.swing.JTextField();
        btnInsertarEmpleado = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaEmpleado = new javax.swing.JTextArea();
        cmbCargo = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txaAntes = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txaDespués = new javax.swing.JTextArea();
        btnRotar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        cbxSucursales = new javax.swing.JComboBox<>();
        btnMostrarEmpleados = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        txaMostrarEmpleados = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblNombres.setText("Nombre");

        lblApellidos.setText("Apellido");

        txtNombres.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNombresKeyPressed(evt);
            }
        });

        jLabel1.setText("Correo electrónico");

        jLabel2.setText("Dirección");

        jLabel3.setText("Número de teléfeno");

        txtApellidos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtApellidosKeyPressed(evt);
            }
        });

        txtDireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDireccionKeyPressed(evt);
            }
        });

        txtCorreo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCorreoKeyPressed(evt);
            }
        });

        txtNumTelf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNumTelfKeyPressed(evt);
            }
        });

        btnInsertarEmpleado.setText("Registrar");
        btnInsertarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarEmpleadoActionPerformed(evt);
            }
        });

        txaEmpleado.setColumns(20);
        txaEmpleado.setRows(5);
        jScrollPane1.setViewportView(txaEmpleado);

        cmbCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vendedor", "Contador", "Encargado de Bodega" }));

        jLabel6.setText("Cargo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblNombres)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtDireccion))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtCorreo))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNumTelf))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblApellidos)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbCargo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtApellidos)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(btnInsertarEmpleado)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNombres)
                            .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblApellidos)
                            .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtNumTelf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnInsertarEmpleado)
                        .addGap(23, 23, 23))))
        );

        jTabbedPane1.addTab("Registro Empleado", jPanel1);

        jLabel4.setText("Lista previa a la rotación");

        txaAntes.setColumns(20);
        txaAntes.setRows(5);
        jScrollPane2.setViewportView(txaAntes);

        jLabel5.setText("Lista después de la rotación");

        txaDespués.setColumns(20);
        txaDespués.setRows(5);
        jScrollPane3.setViewportView(txaDespués);

        btnRotar.setText("Rotar");
        btnRotar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRotarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane3)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(241, 241, 241)
                .addComponent(btnRotar)
                .addContainerGap(274, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRotar)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Rotar Empleados", jPanel2);

        cbxSucursales.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sucursal 1", "Sucursal 2", "Sucursal 3", "Sucursal 4" }));
        cbxSucursales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxSucursalesActionPerformed(evt);
            }
        });

        btnMostrarEmpleados.setText("Mostrar Empleados");
        btnMostrarEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarEmpleadosActionPerformed(evt);
            }
        });

        txaMostrarEmpleados.setColumns(20);
        txaMostrarEmpleados.setRows(5);
        jScrollPane4.setViewportView(txaMostrarEmpleados);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(cbxSucursales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnMostrarEmpleados)
                        .addGap(0, 338, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxSucursales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMostrarEmpleados))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(158, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Consultar", jPanel3);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu1.setText("File");

        jMenuItem3.setText("Salir");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem1.setText("jMenuItem1");
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void btnInsertarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarEmpleadoActionPerformed
        // TODO add your handling code here:
        /*
        Empleado emp = new Empleado();
        String cargo = String.valueOf(cmbCargo.getSelectedItem()); 
        String codigo = "";
        switch(cargo){
            case "Vendedor":
                codigo += "VD";
                codigo += "-";
                codigo += emp.generarDigitos();
                while (empleado.enlace != null && codigo.equals(empleado.codigo)){
                    codigo = "VD";
                    codigo += "-";
                    codigo += emp.generarDigitos();
                    empleado = empleado.enlace;
                }
                
                break;
            case "Contador":
                codigo += "CT";
                codigo += "-";
                codigo += emp.generarDigitos();
                while (empleado.enlace != null && codigo.equals(empleado.codigo)){
                    codigo = "CT";
                    codigo += "-";
                    codigo += emp.generarDigitos();
                    empleado = empleado.enlace;
                }
                break;
            case "Encargado de Bodega":
                codigo += "EB";
                codigo += "-";
                codigo += emp.generarDigitos();
                while (empleado.enlace != null && codigo.equals(empleado.codigo)){
                    codigo = "EB";
                    codigo += "-";
                    codigo += emp.generarDigitos();
                    empleado = empleado.enlace;
                }
                break;
        }
        
        String direccion = txtDireccion.getText();
        
        
        
        
        Empleado nuevoEmpleado = new Empleado(codigo,txtNombres.getText(),txtApellidos.getText(),cargo,direccion,correo,txtNumTelf.getText());
        
        txaEmpleado.setText(nuevoEmpleado.toString());
        */
    }//GEN-LAST:event_btnInsertarEmpleadoActionPerformed

    private void btnRotarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRotarActionPerformed
        // TODO add your handling code here:
        txaAntes.setText(tabla.mostrarEstructura());
        
        
        try{
            FileReader fr = new FileReader("registroEmpleados1.txt");
            BufferedReader br = new BufferedReader(fr);
            
            FileWriter fw = new FileWriter("registroEmpleados1.txt");
            PrintWriter pw = new PrintWriter(fw);
            
            
        }catch(Exception e){
            e.printStackTrace();
        }
        
        
        
        
        
        
        /*
        for(int i = 0; i < 4; i++){
            NodoEmpleado aux = tabla.getNodoEmpleado(i);
            int salida = 1;
            do{
                if(aux.enlace != null){
                    String codAux = aux.getCodigo();
                    int posicion = i;
                    tablaAuxiliar.insertar(posicion, codAux);
                    aux = aux.getEnlace();
                }else{
                    String codAux = aux.getCodigo();
                    int posicion = i;
                    tablaAuxiliar.insertar(posicion, codAux);
                    aux = aux.getEnlace();
                    salida = 0;
                }
                
            }while(salida == 1);
        }
        tabla.vaciarTabla();
        
        for(int i = 0; i < 3; i++){
            NodoEmpleado aux = tablaAuxiliar.getNodoEmpleado(i);
            int salida = 1;
            while(salida == 1){
                if(aux.enlace != null){
                    String codAux = aux.getCodigo();
                    int posicion = i+1;
                    tabla.insertar(posicion, codAux);
                    aux = aux.getEnlace();
                }else{
                    String codAux = aux.getCodigo();
                    int posicion = i+1;
                    tabla.insertar(posicion, codAux);
                    aux = aux.getEnlace();
                    salida = 0;
                }
            }
        }
        
        NodoEmpleado aux = tablaAuxiliar.getNodoEmpleado(3);
        //System.out.println(aux);
        int salida = 1;
        while(salida == 1){
            if(aux.enlace != null){
                    String codigoAux = aux.getCodigo();
                    tabla.insertar(1, codigoAux);
                    aux = aux.getEnlace();
                }else{
                    String codigoAux = aux.getCodigo();
                    tabla.insertar(1, codigoAux);
                    aux = aux.getEnlace();
                    salida = 0;
                }
        }
        
        txaDespués.setText(tabla.mostrarEstructura());
        */
        
        
    }//GEN-LAST:event_btnRotarActionPerformed

    private void cbxSucursalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxSucursalesActionPerformed
        // TODO add your handling code here:
        //sucursal = String.valueOf(cbxSucursales.getSelectedItem());
        
    }//GEN-LAST:event_cbxSucursalesActionPerformed

    private void btnMostrarEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarEmpleadosActionPerformed
        // TODO add your handling code here:
        /*
        if(sucursal.equals("Sucursal 1")){
            txaMostrarEmpleados.setText(sucursal1.mostrarEstructura());
        }else if(sucursal.equals("Sucursal 2")){
            txaMostrarEmpleados.setText(sucursal2.mostrarEstructura());
        }else if(sucursal.equals("Sucursal 3")){
            txaMostrarEmpleados.setText(sucursal3.mostrarEstructura());
        }else if(sucursal.equals("Sucursal 4")){
            txaMostrarEmpleados.setText(sucursal4.mostrarEstructura());
        }
        */
        
    }//GEN-LAST:event_btnMostrarEmpleadosActionPerformed

    private void txtCorreoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCorreoKeyPressed
        // TODO add your handling code here:
        Empleado emp = new Empleado();
        String correo = txtCorreo.getText();
        if(!emp.esCorreoValido(correo)){
            JOptionPane.showMessageDialog(null, "Correo inválido, vuelva a ingresarlo");
            txtCorreo.setText("");
            txtCorreo.requestFocus();
        }else{
            txtNumTelf.requestFocus();
        }
    }//GEN-LAST:event_txtCorreoKeyPressed

    private void txtNumTelfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumTelfKeyPressed
        // TODO add your handling code here:
        Empleado emp = new Empleado();
        String numTelf = txtNumTelf.getText();
        if(!emp.esTelefonoValido(numTelf)){
            JOptionPane.showMessageDialog(null, "Número de teléfono inválido, vuelva a ingresarlo");
            txtNumTelf.setText("");
            txtNumTelf.requestFocus();
        }
    }//GEN-LAST:event_txtNumTelfKeyPressed

    private void txtNombresKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombresKeyPressed
        // TODO add your handling code here:
        Empleado emp = new Empleado();
        String nombre = txtNombres.getText();
        if(!emp.esNombreValido(nombre)){
            JOptionPane.showMessageDialog(null, "Su nombre no puede contener números ni caracteres especiales");
            txtNombres.setText("");
            txtNombres.requestFocus();
        }else{
            txtApellidos.requestFocus();
        }
    }//GEN-LAST:event_txtNombresKeyPressed

    private void txtApellidosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidosKeyPressed
        // TODO add your handling code here:
        Empleado emp = new Empleado();
        String apellido = txtApellidos.getText();
        if(!emp.esApellidoValido(apellido)){
            JOptionPane.showMessageDialog(null, "Su apellido no puede contener números ni caracteres especiales");
            txtApellidos.setText("");
            txtApellidos.requestFocus();
        }else{
            cmbCargo.requestFocus();
        }
    }//GEN-LAST:event_txtApellidosKeyPressed

    private void txtDireccionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDireccionKeyPressed
        // TODO add your handling code here:
        Empleado emp = new Empleado();
        String direccion = txtDireccion.getText();
        if(!emp.esApellidoValido(direccion)){
            JOptionPane.showMessageDialog(null, "Su direccion no puede contener números ni caracteres especiales");
            txtDireccion.setText("");
            txtDireccion.requestFocus();
        }else{
            txtCorreo.requestFocus();
        }
    }//GEN-LAST:event_txtDireccionKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInsertarEmpleado;
    private javax.swing.JButton btnMostrarEmpleados;
    private javax.swing.JButton btnRotar;
    private javax.swing.JComboBox<String> cbxSucursales;
    private javax.swing.JComboBox<String> cmbCargo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblApellidos;
    private javax.swing.JLabel lblNombres;
    private javax.swing.JTextArea txaAntes;
    private javax.swing.JTextArea txaDespués;
    private javax.swing.JTextArea txaEmpleado;
    private javax.swing.JTextArea txaMostrarEmpleados;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextField txtNumTelf;
    // End of variables declaration//GEN-END:variables
}
